"""
Custom exception hierarchy for sigtekx.

Enhanced with research-specific exceptions for benchmarking,
experiments, and reproducibility following RSE/RE standards.
"""

from typing import Any


class SigTekXError(Exception):
    """Base exception for all sigtekx errors.

    Provides consistent error handling with contextual hints and flexible
    context storage for debugging and error tracking.

    Parameters
    ----------
    message : str
        Human-readable error description.
    hint : str, optional
        Contextual hint for resolving the error. May be auto-generated by
        subclasses based on error parameters.
    **kwargs : dict
        Additional context stored in self.context. Common keys include field
        names, values, identifiers, state information, etc.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E000).
    hint : str or None
        Resolution hint (explicit or auto-generated by subclasses).
    context : dict
        Additional error context from kwargs as key-value pairs.

    Examples
    --------
    >>> raise SigTekXError("Operation failed", hint="Check system logs")
    >>> raise SigTekXError("Config error", config_file="config.yaml", line=42)
    """

    error_code = "E000"

    def __init__(self, message: str, hint: str | None = None, **kwargs):
        super().__init__(message)
        self.hint = hint
        self.context = kwargs

    def __str__(self) -> str:
        msg = super().__str__()
        if self.hint:
            msg += f"\nHint: {self.hint}"
        if self.context:
            context_str = ", ".join(f"{k}={v}" for k, v in self.context.items())
            msg += f"\nContext: {context_str}"
        return msg

    def __repr__(self) -> str:
        """Machine-readable representation with error code."""
        return f"{self.__class__.__name__}({self.error_code!r}, {str(self)!r})"


# ============================================================================
# Configuration and Validation Errors
# ============================================================================

class ConfigError(SigTekXError):
    """Configuration validation or compatibility error.

    Raised when configuration parameters are invalid or incompatible.

    Parameters
    ----------
    message : str
        Error description.
    field : str, optional
        Name of the configuration field that failed.
    value : Any, optional
        Invalid value that was provided.
    hint : str, optional
        Custom hint. If None and field is provided, auto-generated as
        "Check the '{field}' field (current value: {value})".

    Attributes
    ----------
    error_code : str
        Stable error identifier (E1010).
    field : str or None
        Configuration field name.
    value : Any
        Invalid value provided.
    hint : str or None
        Resolution hint (explicit or auto-generated).
    context : dict
        Inherited from SigTekXError.
    """

    error_code = "E1010"

    def __init__(
        self,
        message: str,
        field: str | None = None,
        value: Any = None,
        hint: str | None = None,
    ):
        # If no explicit hint provided, build a simple field-based hint
        if hint is None and field:
            hint = f"Check the '{field}' field"
            if value is not None:
                hint += f" (current value: {value})"
        super().__init__(message, hint, field=field, value=value)
        self.field = field
        self.value = value


class ValidationError(SigTekXError):
    """Input data validation error.

    Raised when input data fails validation checks.

    Parameters
    ----------
    message : str
        Error description.
    expected : str, optional
        Expected type or value.
    got : str, optional
        Actual type or value received.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E1020).
    expected : str or None
        Expected type or value.
    got : str or None
        Actual type or value.
    hint : str or None
        Auto-generated as "Expected {expected}, got {got}" if both provided.
    context : dict
        Inherited from SigTekXError.
    """

    error_code = "E1020"

    def __init__(self, message: str, expected: str | None = None, got: str | None = None):
        hint = None
        if expected and got:
            hint = f"Expected {expected}, got {got}"
        super().__init__(message, hint, expected=expected, got=got)
        self.expected = expected
        self.got = got


# ============================================================================
# Hardware and Runtime Errors
# ============================================================================

class DeviceNotFoundError(SigTekXError):
    """No CUDA-capable devices found.

    Raised when GPU detection fails during engine initialization.

    Parameters
    ----------
    message : str, optional
        Custom error message.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E2010).
    hint : str
        Always set to "Ensure NVIDIA drivers are installed and a GPU is present".
    context : dict
        Inherited from SigTekXError (empty for this exception).
    """

    error_code = "E2010"

    def __init__(self, message: str = "No CUDA-capable devices found"):
        hint = "Ensure NVIDIA drivers are installed and a GPU is present"
        super().__init__(message, hint)


class DllLoadError(SigTekXError):
    """Failed to load required DLL/shared library.

    Raised when CUDA or engine library loading fails.

    Parameters
    ----------
    dll_name : str
        Name of the DLL/library that failed to load.
    original_error : Exception, optional
        Original exception from the loading attempt.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E2020).
    dll_name : str
        Name of the failed DLL/library.
    original_error : Exception or None
        Original exception if available.
    hint : str
        Always set to "Check that CUDA toolkit is installed and on PATH".
    context : dict
        Inherited from SigTekXError.
    """

    error_code = "E2020"

    def __init__(self, dll_name: str, original_error: Exception | None = None):
        message = f"Failed to load {dll_name}"
        if original_error:
            message += f": {original_error}"
        hint = "Check that CUDA toolkit is installed and on PATH"
        super().__init__(message, hint, dll_name=dll_name, original_error=original_error)
        self.dll_name = dll_name
        self.original_error = original_error


class EngineStateError(SigTekXError):
    """Engine is in an invalid state for the requested operation.

    Raised when operations are attempted in incorrect engine states.

    Parameters
    ----------
    message : str
        Error description.
    current_state : str, optional
        Current engine state (e.g., "uninitialized", "processing").

    Attributes
    ----------
    error_code : str
        Stable error identifier (E3010).
    current_state : str or None
        Current engine state.
    hint : str or None
        Auto-generated based on state: "uninitialized" suggests calling
        initialize(), "processing" suggests waiting.
    context : dict
        Inherited from SigTekXError.
    """

    error_code = "E3010"

    def __init__(self, message: str, current_state: str | None = None):
        hint = None
        if current_state == "uninitialized":
            hint = "Call initialize() or use the Engine context manager"
        elif current_state == "processing":
            hint = "Wait for current operation to complete"
        super().__init__(message, hint, current_state=current_state)
        self.current_state = current_state


class EngineRuntimeError(SigTekXError):
    """Runtime error during engine processing.

    Raised when CUDA operations or engine processing fails.

    Parameters
    ----------
    message : str
        Error description.
    cuda_error : str, optional
        CUDA error message if available.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E3020).
    cuda_error : str or None
        CUDA error message.
    hint : str or None
        Auto-generated based on error: "out of memory" suggests reducing
        parameters, "invalid configuration" suggests validation.
    context : dict
        Inherited from SigTekXError.
    """

    error_code = "E3020"

    def __init__(self, message: str, cuda_error: str | None = None):
        hint = None
        if cuda_error:
            if "out of memory" in cuda_error.lower():
                hint = "Reduce channels or nfft, or use a GPU with more memory"
            elif "invalid configuration" in cuda_error.lower():
                hint = "Check that nfft is a power of 2 and channels > 0"
        super().__init__(message, hint, cuda_error=cuda_error)
        self.cuda_error = cuda_error


# ============================================================================
# Research and Benchmarking Errors (NEW)
# ============================================================================

class BenchmarkError(SigTekXError):
    """Base class for benchmark-related errors.

    Raised during benchmark execution, validation, or analysis phases.

    Parameters
    ----------
    message : str
        Error description.
    benchmark_name : str, optional
        Name of the benchmark that raised this exception.
    **kwargs : dict
        Additional context passed to SigTekXError.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E4000).
    benchmark_name : str or None
        Benchmark identifier for error tracking.
    hint : str or None
        Inherited from SigTekXError.
    context : dict
        Inherited from SigTekXError.
    """

    error_code = "E4000"

    def __init__(self, message: str, benchmark_name: str | None = None, **kwargs):
        super().__init__(message, benchmark_name=benchmark_name, **kwargs)
        self.benchmark_name = benchmark_name


class BenchmarkTimeoutError(BenchmarkError):
    """Benchmark iteration exceeded timeout.

    Raised when a benchmark iteration takes longer than the specified timeout.

    Parameters
    ----------
    benchmark_name : str
        Name of the benchmark.
    iteration : int
        Iteration number that timed out.
    timeout_s : float
        Timeout value in seconds.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E4100).
    benchmark_name : str
        Inherited from BenchmarkError.
    hint : str
        Always set to "Consider increasing timeout or optimizing the benchmark".
    context : dict
        Inherited from BenchmarkError. Includes iteration and timeout_s.
    """

    error_code = "E4100"

    def __init__(self, benchmark_name: str, iteration: int, timeout_s: float):
        message = f"Benchmark '{benchmark_name}' iteration {iteration} exceeded {timeout_s}s timeout"
        hint = "Consider increasing timeout or optimizing the benchmark"
        super().__init__(message, benchmark_name, iteration=iteration, timeout_s=timeout_s, hint=hint)


class BenchmarkValidationError(BenchmarkError):
    """Benchmark results failed validation.

    Raised when benchmark results fail validation checks or exceed thresholds.

    Parameters
    ----------
    benchmark_name : str
        Name of the benchmark.
    reason : str
        Reason for validation failure.
    metrics : dict[str, Any], optional
        Metrics that failed validation.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E4110).
    benchmark_name : str
        Inherited from BenchmarkError.
    reason : str
        Validation failure reason.
    metrics : dict[str, Any] or None
        Failed metrics as key-value pairs.
    hint : str
        Always set to "Check benchmark configuration and system performance".
    context : dict
        Inherited from BenchmarkError. Includes reason and metrics.
    """

    error_code = "E4110"

    def __init__(self, benchmark_name: str, reason: str, metrics: dict[str, Any] | None = None):
        message = f"Benchmark '{benchmark_name}' failed validation: {reason}"
        hint = "Check benchmark configuration and system performance"
        super().__init__(message, benchmark_name, reason=reason, metrics=metrics, hint=hint)
        self.reason = reason
        self.metrics = metrics


class ExperimentError(SigTekXError):
    """Base class for experiment-related errors.

    Raised during experiment setup, execution, or tracking phases.

    Parameters
    ----------
    message : str
        Error description.
    experiment_id : str, optional
        Unique identifier for the experiment.
    **kwargs : dict
        Additional context passed to SigTekXError.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E4010).
    experiment_id : str or None
        Experiment identifier for error tracking.
    hint : str or None
        Inherited from SigTekXError.
    context : dict
        Inherited from SigTekXError.
    """

    error_code = "E4010"

    def __init__(self, message: str, experiment_id: str | None = None, **kwargs):
        super().__init__(message, experiment_id=experiment_id, **kwargs)
        self.experiment_id = experiment_id




class ReproducibilityError(SigTekXError):
    """Error related to research reproducibility.

    Raised when reproducibility metadata is missing or incomplete.

    Parameters
    ----------
    message : str
        Error description.
    missing_info : list[str], optional
        List of missing metadata fields.
    **kwargs : dict
        Additional context passed to SigTekXError.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E4200).
    missing_info : list[str] or None
        Names of missing reproducibility metadata fields.
    hint : str or None
        Auto-generated as "Missing reproducibility information: {list}".
    context : dict
        Inherited from SigTekXError.

    Examples
    --------
    >>> raise ReproducibilityError(
    ...     "Incomplete experiment metadata",
    ...     missing_info=["git_commit", "python_version", "cuda_version"]
    ... )
    """

    error_code = "E4200"

    def __init__(self, message: str, missing_info: list[str] | None = None, **kwargs):
        hint = None
        if missing_info:
            hint = f"Missing reproducibility information: {', '.join(missing_info)}"
        super().__init__(message, hint=hint, missing_info=missing_info, **kwargs)
        self.missing_info = missing_info


class EnvironmentMismatchError(ReproducibilityError):
    """Environment doesn't match expected configuration for reproduction.

    Raised when attempting to reproduce results in a different environment.

    Parameters
    ----------
    expected : dict[str, Any]
        Expected environment configuration.
    actual : dict[str, Any]
        Actual environment configuration.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E4210).
    expected : dict[str, Any]
        Expected environment (passed to constructor).
    actual : dict[str, Any]
        Actual environment (passed to constructor).
    differences : list[str]
        Auto-calculated mismatches. Format: "key: expected=val1, actual=val2".
        Computed in __init__ by comparing expected vs actual dicts.
    missing_info : list[str] or None
        Inherited from ReproducibilityError (set to differences).
    hint : str or None
        Inherited from ReproducibilityError (auto-generated from differences).

    Examples
    --------
    >>> raise EnvironmentMismatchError(
    ...     {"cuda": "11.8", "driver": "525.60"},
    ...     {"cuda": "12.0", "driver": "525.60"}
    ... )
    """

    error_code = "E4210"

    def __init__(self, expected: dict[str, Any], actual: dict[str, Any]):
        differences = []
        for key in expected:
            if key in actual and expected[key] != actual[key]:
                differences.append(f"{key}: expected={expected[key]}, actual={actual[key]}")

        message = "Environment mismatch detected"
        if differences:
            message += f": {'; '.join(differences[:3])}"  # Show first 3 differences
            if len(differences) > 3:
                message += f" (and {len(differences)-3} more)"

        super().__init__(message, expected=expected, actual=actual, differences=differences)
        self.expected = expected
        self.actual = actual
        self.differences = differences


class DataIntegrityError(SigTekXError):
    """Data corruption or integrity check failure.

    Raised when data checksum or hash validation fails.

    Parameters
    ----------
    message : str
        Error description.
    expected_hash : str, optional
        Expected checksum/hash value.
    actual_hash : str, optional
        Actual checksum/hash value computed.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E4220).
    expected_hash : str or None
        Expected hash value.
    actual_hash : str or None
        Actual hash value.
    hint : str
        Always starts with "Data may be corrupted or modified". If hashes
        provided, appends truncated hash comparison (first 8 chars).
    context : dict
        Inherited from SigTekXError.

    Examples
    --------
    >>> raise DataIntegrityError(
    ...     "Benchmark results file corrupted",
    ...     expected_hash="a1b2c3d4e5f6...",
    ...     actual_hash="fedcba987654..."
    ... )
    """

    error_code = "E4220"

    def __init__(self, message: str, expected_hash: str | None = None, actual_hash: str | None = None):
        hint = "Data may be corrupted or modified"
        if expected_hash and actual_hash:
            hint += f" (hash mismatch: expected {expected_hash[:8]}..., got {actual_hash[:8]}...)"
        super().__init__(message, hint=hint, expected_hash=expected_hash, actual_hash=actual_hash)
        self.expected_hash = expected_hash
        self.actual_hash = actual_hash


# ============================================================================
# Analysis and Reporting Errors
# ============================================================================

class AnalysisError(SigTekXError):
    """Error during result analysis.

    Raised when statistical or data analysis operations fail.

    Parameters
    ----------
    message : str
        Error description.
    analysis_type : str, optional
        Type of analysis (e.g., 'scaling', 'latency', 'throughput').
    **kwargs : dict
        Additional context passed to SigTekXError.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E5000).
    analysis_type : str or None
        Analysis type identifier.
    hint : str or None
        Inherited from SigTekXError.
    context : dict
        Inherited from SigTekXError.
    """

    error_code = "E5000"

    def __init__(self, message: str, analysis_type: str | None = None, **kwargs):
        super().__init__(message, analysis_type=analysis_type, **kwargs)
        self.analysis_type = analysis_type


class ReportGenerationError(SigTekXError):
    """Error generating benchmark report.

    Raised when report generation fails due to missing dependencies or templates.

    Parameters
    ----------
    message : str
        Error description.
    report_format : str, optional
        Report format (e.g., 'pdf', 'html', 'markdown').
    **kwargs : dict
        Additional context passed to SigTekXError.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E5020).
    report_format : str or None
        Requested report format.
    hint : str or None
        Auto-generated based on format: 'pdf' suggests checking matplotlib,
        'html' suggests checking templates.
    context : dict
        Inherited from SigTekXError.
    """

    error_code = "E5020"

    def __init__(self, message: str, report_format: str | None = None, **kwargs):
        hint = None
        if report_format == "pdf":
            hint = "Ensure matplotlib and required fonts are installed"
        elif report_format == "html":
            hint = "Check that all template files are available"
        super().__init__(message, hint=hint, report_format=report_format, **kwargs)
        self.report_format = report_format


class InsufficientDataError(AnalysisError):
    """Not enough data for statistical analysis.

    Raised when sample size is below the minimum required for valid analysis.

    Parameters
    ----------
    required : int
        Minimum required number of samples.
    actual : int
        Actual number of samples available.
    analysis_type : str, optional
        Type of analysis requiring the data.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E5010).
    required : int
        Minimum sample count required.
    actual : int
        Actual sample count available.
    analysis_type : str or None
        Inherited from AnalysisError.
    hint : str
        Always set to "Increase number of iterations or check data collection".
    context : dict
        Inherited from AnalysisError. Includes required and actual.
    """

    error_code = "E5010"

    def __init__(self, required: int, actual: int, analysis_type: str | None = None):
        message = f"Insufficient data: need {required} samples, got {actual}"
        hint = "Increase number of iterations or check data collection"
        super().__init__(message, analysis_type=analysis_type, required=required, actual=actual, hint=hint)
        self.required = required
        self.actual = actual


# ============================================================================
# Workflow and Orchestration Errors
# ============================================================================

class WorkflowError(SigTekXError):
    """Error in research workflow execution.

    Raised when workflow orchestration or pipeline execution fails.

    Parameters
    ----------
    message : str
        Error description.
    workflow_stage : str, optional
        Current workflow stage (e.g., 'data_collection', 'analysis').
    **kwargs : dict
        Additional context passed to SigTekXError.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E6000).
    workflow_stage : str or None
        Workflow stage identifier.
    hint : str or None
        Inherited from SigTekXError.
    context : dict
        Inherited from SigTekXError.
    """

    error_code = "E6000"

    def __init__(self, message: str, workflow_stage: str | None = None, **kwargs):
        super().__init__(message, workflow_stage=workflow_stage, **kwargs)
        self.workflow_stage = workflow_stage


class DependencyError(WorkflowError):
    """Required dependency not met.

    Raised when required packages or modules are missing or incompatible.

    Parameters
    ----------
    message : str
        Error description.
    missing_dependencies : list[str], optional
        List of missing package/module names.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E6010).
    missing_dependencies : list[str] or None
        Names of missing dependencies.
    workflow_stage : str or None
        Inherited from WorkflowError.
    hint : str or None
        Auto-generated as "Install missing dependencies: {list}" if provided.
    context : dict
        Inherited from WorkflowError.
    """

    error_code = "E6010"

    def __init__(self, message: str, missing_dependencies: list[str] | None = None):
        hint = None
        if missing_dependencies:
            hint = f"Install missing dependencies: {', '.join(missing_dependencies)}"
        super().__init__(message, missing_dependencies=missing_dependencies, hint=hint)
        self.missing_dependencies = missing_dependencies


class ResourceExhaustedError(SigTekXError):
    """System resource exhausted (memory, disk, etc.).

    Raised when system resources are insufficient for the requested operation.

    Parameters
    ----------
    resource_type : str
        Type of resource (e.g., 'gpu memory', 'disk space', 'file handles').
    required : Any, optional
        Amount of resource required.
    available : Any, optional
        Amount of resource available.

    Attributes
    ----------
    error_code : str
        Stable error identifier (E6020).
    resource_type : str
        Resource type that was exhausted.
    required : Any
        Required resource amount.
    available : Any
        Available resource amount.
    hint : str or None
        Auto-generated based on resource_type: 'gpu memory' suggests reducing
        parameters, 'disk space' suggests cleanup.
    context : dict
        Inherited from SigTekXError.
    """

    error_code = "E6020"

    def __init__(self, resource_type: str, required: Any = None, available: Any = None):
        message = f"{resource_type} exhausted"
        if required and available:
            message += f": required {required}, available {available}"

        hint = None
        if resource_type.lower() == "gpu memory":
            hint = "Reduce channels or nfft"
        elif resource_type.lower() == "disk space":
            hint = "Clean up old results or increase storage"

        super().__init__(message, hint=hint, resource_type=resource_type,
                        required=required, available=available)
        self.resource_type = resource_type
        self.required = required
        self.available = available
