name: ionosense-hpc
channels:
  - nvidia
  - conda-forge
channel_priority: strict
dependencies:
  # Core
  - python=3.11
  - cmake>=3.26
  - ninja

  # VS Build tools
  - vs2022_win-64

  # CUDA toolchain (NVCC + dev libs)
  - cuda-compiler=13.0
  - cuda-libraries-dev=13.0

  # Python stack
  - numpy
  - pybind11
  - pytest
  - tqdm
  - colorama
  - scipy
  - pandas
  - matplotlib
  - h5py
  # Testing
  - pytest
  - pytest-xdist
  # Dev Tools
  - pre-commit
  - pip
