name: ionosense-hpc
channels:
  - conda-forge
  - nvidia
channel_priority: strict
dependencies:
  # Core
  - python=3.11
  - cmake
  - ninja
  # C++
  - pybind11
  # Python Libs
  - numpy
  - scipy
  - matplotlib
  - pandas
  - py-cpuinfo
  # Testing
  - pytest
  - pytest-xdist
  # Dev Tools
  - pre-commit
  - pip
