# pytest.ini
[pytest]
minversion = 7.0
testpaths = python/tests
addopts = --import-mode=importlib --color=yes -ra

markers =
    config: tests for the configuration module
    signals: tests for the signal generation utilities

xfail_strict = true
filterwarnings =
    error
    ignore::DeprecationWarning:numpy.*
    ignore::DeprecationWarning:pkg_resources.*

log_cli = true
log_cli_level = INFO
